#!/bin/bash

echo "WARNING: THIS WILL OVERWRITE ALL DATA ON THIS DISK"
echo
echo "Please enter the name of the disk you would like to partition: "

read drive

if ! fdisk -l | grep -q " $drive:";
then
echo "Please enter a valid drive name"
exit 0
fi

echo "Please enter the amount of GB you would like to allocate to root: "

read root

echo "Please enter your timezone. You can find this in the /etc/locale.gen file: "

read tz

ask_root_pwd () {
    echo "Please enter your password for root: "

    read -s rootpwd

    echo "Please conmfirm your password for root: "

    read -s rootpwdvalid
}

while [ $rootpwd != $rootpwdvalid ]
do
ask_root_pwd
done

echo "Please enter your user name: "

read user

ask_pwd () {
    echo "Please enter your password: "

    read -s pwd

    echo "Please conmfirm your password: "

    read -s pwdvalid
}

while [ $pwd != $pwdvalid ]
do
ask_pwd
done

#################################

echo -e "g\nn\n\n\n+500M\nt\n1\nn\n\n\n\nt\n\n30\nw\n" | fdisk $drive

mkfs.fat -F32 ${drive}1

pvcreate --dataalignment 1m ${drive}2

vgcreate volgroup0 ${drive}2
lvcreate -L ${root}GB volgroup0 -n root
lvcreate -l 100%FREE volgroup0 -n home

modeprobe dm_mod
vgscan
vgchange -ay

mkfs.ext4 /dev/volgroup0/root
mount /dev/volgroup0/root /mnt

mkfs.ext4 /dev/volgroup0/home
mkdir /mnt/home
mount /dev/volgroup0/home /mnt/home

genfstab -U /mnt >> /mnt/etc/fstab

echo -e "Y\n" | pacstrap -i /mnt base

arch-chroot /mnt << EOM

echo -e "1\nY\n" | pacman -S linux-lts linux-lts-headers linux-firmware
echo | pacman -S nano
echo -e "\nY\n" | pacman -S base-devel openssh
echo -e "\nY\n" | pacman -S networkmanager wpa_supplicant wireless_tools netctl
echo | pacman -S lvm2

systemctl enable sshd
systemctl enable NetworkManager

sed -i 's/HOOKS=(base udev autodetect modconf block filesystems keyboard fsck)/\
HOOKS=(base udev autodetect modconf block lvm2 filesystems keyboard fsck)/' /etc/mkinitcpio.conf

mkinitcpio -p linux-lts

sed -i 's/#'"${tz}"'.UTF-8 UTF-8/'"${tz}"'.UTF-8 UTF-8/' /etc/locale.gen
locale-gen

echo -e "$rootpwd\n$rootpwd\n" | passwd

useradd -m -g users -G wheel $user
echo -e "$pwd\n$pwd\n" | passwd $user

sed -i 's/# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/' /etc/sudoers

echo | pacman -S grub efibootmgr dosfstools os-prober mtools

mkdir /boot/EFI

mount ${drive}1 /boot/EFI

grub-install --target=x86_64-efi --bootloader-id=grub_uefi --recheck

cp /usr/share/locale/en\@quot/LC_MESSAGES/grub.mo /boot/grub/locale/en.mo

grub-mkconfig -o /boot/grub/grub.cfg

EOM

umount -a
