#!/bin/bash

get_drive () {
    echo "WARNING: THIS WILL OVERWRITE ALL DATA ON THIS DISK"
    echo
    echo "Please enter the name of the disk you would like to partition: "
    read drive
}

get_drive

while ! fdisk -l | grep -q " $drive:"
do
echo "Please enter a valid drive name"
get_drive
done

echo "Please enter the amount of GB you would like to allocate to root: "
read root

get_tz () {
    echo "Please enter your timezone for locale.gen. You can find this in the /etc/locale.gen file: "
    read tz
}

get_tz

while ! cat /etc/locale.gen | grep -q $tz
do
echo "Please enter a valid timezone"
get_tz
done

ask_root_pwd () {
    echo "Please enter your password for root: "
    read -s rootpwd
    echo "Please conmfirm your password for root: "
    read -s rootpwdvalid
}

ask_root_pwd

while [ $rootpwd != $rootpwdvalid ]
do
echo "Passwords do not match"
ask_root_pwd
done

echo "Please enter your user name: "

read user

ask_pwd () {
    echo "Please enter your password: "
    read -s pwd
    echo "Please conmfirm your password: "
    read -s pwdvalid
}

ask_pwd

while [ $pwd != $pwdvalid ]
do
echo "Passwords do not match"
ask_pwd
done

echo "Please enter the amount of GB you would like to allocate to swap (half of your total RAM is recommended): "

read swap

get_tz_service () {
    echo "Please enter your timezone. You can find this with timedatectl list-timezones: "

    read tz_service
}

get_tz_service

while ! timedatectl list-timezones | grep -q $tz_service
do
echo "Please enter a valid timezone"
get_tz_service
done

#################################

echo -e "g\nn\n\n\n+500M\nt\n1\nn\n\n\n\nt\n\n30\nw\n" | fdisk $drive

mkfs.fat -F32 ${drive}1

pvcreate --dataalignment 1m ${drive}2

vgcreate volgroup0 ${drive}2
lvcreate -L ${root}GB volgroup0 -n root
lvcreate -l 100%FREE volgroup0 -n home

modeprobe dm_mod
vgscan
vgchange -ay

mkfs.ext4 /dev/volgroup0/root
mount /dev/volgroup0/root /mnt

mkfs.ext4 /dev/volgroup0/home
mkdir /mnt/home
mount /dev/volgroup0/home /mnt/home

genfstab -U /mnt >> /mnt/etc/fstab

echo -e "Y\n" | pacstrap -i /mnt base

arch-chroot /mnt << EOM

echo -e "1\nY\n" | pacman -S linux-lts linux-lts-headers linux-firmware
echo | pacman -S nano
echo -e "\nY\n" | pacman -S base-devel openssh
echo -e "\nY\n" | pacman -S networkmanager wpa_supplicant wireless_tools netctl
echo | pacman -S lvm2

systemctl enable sshd
systemctl enable NetworkManager

sed -i 's/HOOKS=(base udev autodetect modconf block filesystems keyboard fsck)/\
HOOKS=(base udev autodetect modconf block lvm2 filesystems keyboard fsck)/' /etc/mkinitcpio.conf

mkinitcpio -p linux-lts

sed -i 's/#'"${tz}"'.UTF-8 UTF-8/'"${tz}"'.UTF-8 UTF-8/' /etc/locale.gen
locale-gen

echo -e "$rootpwd\n$rootpwd\n" | passwd

useradd -m -g users -G wheel $user
echo -e "$pwd\n$pwd\n" | passwd $user

sed -i 's/# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/' /etc/sudoers

echo | pacman -S grub efibootmgr dosfstools os-prober mtools

mkdir /boot/EFI

mount ${drive}1 /boot/EFI

grub-install --target=x86_64-efi --bootloader-id=grub_uefi --recheck

cp /usr/share/locale/en\@quot/LC_MESSAGES/grub.mo /boot/grub/locale/en.mo

grub-mkconfig -o /boot/grub/grub.cfg

cd root

dd if=/dev/zero of=/swapfile bs=1M count=$((swap*1024)) status=progress

chmod 600 /swapfile

mkswap /swapfile

cp /etc/fstab /etc/fstab.bak

echo '/swapfile none swap sw 0 0' | tee -a /etc/fstab

mount -a

swapon -a

timedatectl set-timezone $tz_service

systemctl enable systemd-timesyncd

EOM

umount -a